name: MLOPS CI CD Pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-train: 
    runs-on: ubuntu-latest

    steps:
      #step 1 - check out source code
      - name: Checkout repositery
        uses: actions/checkout@v4

      #step 2 - Setup Python Environment
      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.10"

      #step 3 - Install Dependencies 
      - name: Install Dependencies
        run: |
          python -m pip insatll --upgrade pip
          pip insatll -r requirements.txt

      #step 4 - Run unit tests
      - name: Run Unit test
        run: pytest -v

      #step 5 - Train the model 
      - name: Train model
        run: python src/train.py

      #step 6 - Evaluate the model
      - name: Evaluate model
        run: python src/evaluate.py

      #step 7 - upload the train model as artifact
      - name: Upload model artifact
        uses: actions/upload-artifact@v4

        with:
          name: Trained-model
          path: models/models.pkl

      
  deploy:
    needs: build-test-train
    runs-on: ubuntu-latest

    steps:
      #step 8 - Download the train model 
      - name: Download model artifact
        uses: actions/download-artifact@v4

        with:
           name: train model 
           path: models

      #step 9 - Deployment simultions
      - name: Deployment simultions
        run: |
          echo "Model deploye successfully"
          ls -l models

